### ISSUE TITLE
dynamic  element can not set color

### ISSUE THREAD

**Issue by xinggg22** [evoluteur/colorpicker#18]
I use Jquery create element, and then add colorpicker to the element...but after select color the input is not effective...
The code like this:
HTML tag:
div id="pColor"

Javascript:

$(document).ready(function(){
    var html='<'+'input type="text" class="colorpicker">';
    $('#pColor').html(html);
    $('.colorpicker').colorpicker({ history: false,transparentColor: true});
});

**Comment by evoluteur** [comment]
I pasted your code into the project's index.html (also created the new div pColor) and it's working fine.
Please create a JSFiddle for me to see the problem. Thanks.
