### ISSUE TITLE
Anonymous wrapper with inline styles prevent custom styling

### ISSUE THREAD

**Issue by bago** [evoluteur/colorpicker#29]
In order to customize the picker style using CSS I had to remove the anonymous (no class) div wrapper added by default by colorpicker. I adds an inline style with hardcoded width and makes it hard to style it:
```
					.wrap('<div style="width:'+(this.options.hideButton?this.element.width():this.element.width()+32)+'px;'+
						(isIE?'margin-bottom:-21px;':'')+
						(isMoz?'padding:1px 0;':'')+
						'"></div>') 
```

![colorpicker-custom-style](https://cloud.githubusercontent.com/assets/173498/9379667/1b9221b4-472b-11e5-9ddb-e17d99a30343.png)

Maybe adding a class to that object would help customizing it. WDYT?

**Comment by evoluteur** [comment]
Good idea. Done. I added a class called "evo-cp-wrap".
