### ISSUE TITLE
 Uncaught Error: cannot call methods on colorpicker prior to initialization; attempted to call method 'destroy'

### ISSUE THREAD

**Issue by dzlixu** [evoluteur/colorpicker#37]
this is my code:
`$('#fontcolor').click(function(){
        $("#colorlist").colorpicker({
            displayIndicator: false,
            hideButton: true,
            strings:"主题颜色,标准颜色,Web 颜色,主题颜色,返回取色板,历史记录,没有历史记录"
        });
    });
    $("#colorlist").on("change.color", function(event, color){
        $('#fontcolor>div').css('color',color);
        $('#colorlist').colorpicker("destroy");
    });`

**Comment by evoluteur** [comment]
It should just be initialized first. I believe it is standard behavior.
