### ISSUE TITLE
Could you add a custom color select tab like this?

### ISSUE THREAD

**Issue by bf185003** [evoluteur/colorpicker#54]
![image](https://user-images.githubusercontent.com/23185348/47416396-3779b200-d7a8-11e8-9413-2d3a4529b679.png)

**Comment by evoluteur** [comment]
It is nice, but a very different style than what I had in mind for my color picker. I wanted to make a simple one (even though it offers less color choices). There are a few color pickers like that, if people prefer that style or all possible colors they can choose these widgets.
I appreciate the suggestion though.
