### ISSUE TITLE
r.widget is not a function

### ISSUE THREAD

**Issue by fuadchonora** [evoluteur/colorpicker#63]
evol-colorpicker.min.js:7 
Uncaught TypeError: r.widget is not a function
    at evol-colorpicker.min.js:7
    at evol-colorpicker.min.js:7
(anonymous) @ evol-colorpicker.min.js:7
(anonymous) @ evol-colorpicker.min.js:7

**Comment by evoluteur** [comment]
I cannot reproduce the problem.

**Comment by GHPS** [comment]
Just a short hint: The error is caused by a missing JQueryUI.
