### ISSUE TITLE
jQuery UI Cross-site Scripting when refreshing a checkboxradio with an HTML-like initial text label #9 

### ISSUE THREAD

**Issue by captproton** [evoluteur/colorpicker#77]
Dependabot cannot update jquery-ui to a non-vulnerable version

The latest possible version that can be installed is 1.12.1 because of the following conflicting dependency:

evol-colorpicker@3.4.3 requires jquery-ui@~1.12.1

The earliest fixed version is 1.13.2.

https://share.getcloudapp.com/kpu8GWnk

**Comment by evoluteur** [comment]
There is no checkboxradio in ColorPicker so that doesn't apply.
